# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request/logRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18request/logRequest.proto\x12\x07request\"I\n\x0brequestCall\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\t\x12\r\n\x05\x64\x65lta\x18\x03 \x01(\t\x12\x0f\n\x07pattern\x18\x04 \x01(\t\"\x1a\n\x08response\x12\x0e\n\x06result\x18\x01 \x01(\t2G\n\nlogRequest\x12\x39\n\x0elogMessageFind\x12\x14.request.requestCall\x1a\x11.request.responseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'request.logRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTCALL._serialized_start=37
  _REQUESTCALL._serialized_end=110
  _RESPONSE._serialized_start=112
  _RESPONSE._serialized_end=138
  _LOGREQUEST._serialized_start=140
  _LOGREQUEST._serialized_end=211
# @@protoc_insertion_point(module_scope)
